application: exaltedsheet
version: 1-1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: javascript

- url: /_ah/channel/.*
  script: connectionManager.py
  
- url: /tokenrequest
  script: connectionManager.py
  login: required

- url: /chat/.*
  script: chat.py
  login: required

inbound_services:
- channel_presence
